<script setup>
  definePageMeta({
    pageTitle: 'Kobeni | Widget Behaviour',
  })

  // all widget states
  const autoLaunchWidget = useState('autoLaunchWidget')
  const widgetStyle = useState('widgetStyle')
  const maskCvv = useState('maskCvv')
  const requireCvv = useState('requireCvv')
  const showCVVHint = useState('showCVVHint')
  const allowEmptyCvv = useState('allowEmptyCvv')
  const validation = useState('validation')
  const showLabels = useState('showLabels')
  const showPlaceholders = useState('showPlaceholders')
  const disableCardExpiryDateValidation = useState(
    'disableCardExpiryDateValidation'
  )

  //
  const payNowLabel = useState('payNowLabel')
  const labelBrand = useState('labelBrand')
  const cardNumber = useState('cardNumber')
  const expiryDate = useState('expiryDate')
  const cardHolder = useState('cardHolder')
  const cvv = useState('cvv')

  const locale = useState('locale')

  //
  const localeList = getLocaleList()
  const shopperResultURLPayon = useState('shopperResultUrlPayon')
</script>

<template>
  <div class="flex flex-col space-y-16">
    <div></div>

    <!-- redirect URL row -->
    <div class="flex gap-10">
      <div class="flex-none w-96 space-y-2">
        <div class="prose">
          <h3 class="text-sky-400 font-bold">Redirect URL</h3>
        </div>

        <p class="text-sm">
          This is auto-generated by this app but you are still free to input a
          different URL where you would like to redirect the user after the
          transaction.
        </p>
      </div>
      <div class="flex-1">
        <Input
          label="shopperResultUrl"
          type="text"
          helper-text="The customer/user is redirected here"
          v-model="shopperResultURLPayon" />
      </div>
    </div>

    <hr />

    <!-- labels row -->
    <div class="flex gap-10">
      <div class="flex-none w-96 space-y-2">
        <div class="prose">
          <h3 class="text-sky-400 font-bold">Labels</h3>
        </div>

        <p class="text-sm">
          These are the widget fields that can be replaced from the default. Go
          ahead, give it a personality.
        </p>

        <p class="text-sm">
          If you prefer the boring defaults, set the fields to blank.
        </p>
      </div>
      <div class="flex-1 space-y-2">
        <Input label="Brand List" v-model="labelBrand" />

        <Input label="Card Number" v-model="cardNumber" />

        <Input label="Expiry Date" v-model="expiryDate" />

        <Input label="Card Holder" v-model="cardHolder" />

        <Input label="CVV" v-model="cvv" />

        <Input label="Card Submit ('PAY NOW' button)" v-model="payNowLabel" />

        <!-- select locale -->
        <div>
          <label class="label">
            <span class="label-text text-sky-400 font-bold">
              Locale (Widget Language)
            </span>
          </label>
          <select class="select select-bordered w-full" v-model="locale">
            <option v-for="local in localeList" :value="local.value">
              {{ local.text }}
            </option>
          </select>
          <label class="label">
            <span class="label-text-alt">
              For this to work, the labels above should be blank.
            </span>
          </label>
        </div>
      </div>
    </div>

    <hr />

    <!-- toggles -->
    <div class="flex flex-col gap-2">
      <Alert title="Info" color-style="bg-sky-900 text-slate-300">
        The following are most the property names that can be toggled in the
        <kbd class="kbd kbd-sm">wpwl</kbd>
        object which customizes the widget. Some of the items here have been
        changed from the default setting to better suit the app's look and flow.
        Additionally, the items labeled as
        <span class="font-medium font-mono text-sky-400">Exclusive</span> are
        features custom-made only for this app.
      </Alert>

      <!-- auto-launch -->
      <Toggle v-model="autoLaunchWidget" title="Auto-launch (Exclusive)">
        Launch the widget if a checkout ID is detected.
      </Toggle>

      <!-- plain vs card -->
      <div
        class="form-control w-auto transition hover:bg-slate-800 p-3 rounded-lg">
        <label class="label cursor-pointer">
          <span class="label-text">
            <span class="text-sky-400 font-bold"><kbd>Card Style</kbd></span
            ><br />
            Set the widget's style to
            <span class="text-sky-400">card</span> (This will some cause
            visibility issues because of this app's theme). Current default:
            <span class="text-sky-400">'plain'</span>.</span
          >
          <input
            type="checkbox"
            class="toggle"
            v-model="widgetStyle"
            true-value="card"
            false-value="plain" />
        </label>
      </div>

      <Toggle
        v-model="disableCardExpiryDateValidation"
        title="disableCardExpiryDateValidation">
        Determines whether the card expiry date field should be validated. By
        default it is validated (false).
      </Toggle>

      <Toggle v-model="requireCvv" title="requireCvv">
        Determines whether the CVV field is presented on the payment form.
      </Toggle>

      <Toggle v-model="maskCvv" title="maskCvv"> Masks the CVV. </Toggle>

      <Toggle v-model="showCVVHint" title="showCVVHint">
        If set to true, then the credit card form will display a hint on where
        the CVV is located when the mouse is hovering over the CVV field.
      </Toggle>

      <Toggle v-model="allowEmptyCvv" title="allowEmptyCvv">
        Determines whether the CVV field can be empty. By default it is false.
      </Toggle>

      <Toggle v-model="validation" title="validation">
        If false, disables validation and the functions
        <kbd class="font-semibold">validate</kbd> and
        <kbd class="font-semibold">onSubmit</kbd> will not be called.
      </Toggle>

      <Toggle v-model="showLabels" title="showLabels">
        Shows or hides input labels. Default is true.
      </Toggle>

      <Toggle v-model="showPlaceholders" title="showPlaceholders">
        Shows or hides input placeholders. Default is true.
      </Toggle>
    </div>
  </div>
</template>
